<a href="https://colab.research.google.com/github/Arnav-Barman/UML501-ML/blob/main/UML501_Lab_29_7_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a1.ndim
#number of dim, columns, features

2

In [16]:
a1.shape

(3, 3)

In [17]:
a1.size

9

In [12]:
a.dtype
# type of elements in array

dtype('int64')

In [18]:
a2=np.array([[1,2],[3,4]])
a3=np.array([[5,6],[7,8]])

In [20]:
np.concatenate((a2,a3),axis=0)
# axis = 0 for y axis

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
np.concatenate((a2,a3),axis=1)
# axis = 1 for x axis

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [22]:
np.arange(1,10,1)
# from 1 to 10 in steps of 1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(1,10,15)
# specify the number of elements that we wish to generate between the first and last element

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])